# Generated by Django 3.0.5 on 2020-04-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_path', models.TextField(blank=True, null=True)),
                ('fk_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showbylikeapp.Posts')),
            ],
        ),
    ]
