# Generated by Django 3.0.5 on 2020-04-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showbylikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='images',
            name='fk_posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='showbylikeapp.Posts'),
        ),
    ]
