# Generated by Django 3.0.5 on 2020-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showbylikeapp', '0002_auto_20200416_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='txt_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
