# Generated by Django 3.0.5 on 2020-04-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showbylikeapp', '0005_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='txt_path',
            new_name='txt_file_name',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='fk_tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='chr_tag2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
