# Generated by Django 3.0.5 on 2020-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showbylikeapp', '0006_auto_20200417_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='int_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
